Sinbin.Web/Controllers/FeedController.cs
using Sinbin.UserManager;
using Sinbin.Web.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Sinbin.Web.Controllers
{
    [Authorize]
    public class FeedController : Controller
    {
        private readonly FeedManager _manager;

        public FeedController()
        {
            _manager = new FeedManager();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        // Feed/Feed
        [HttpGet]
        [Authorize]
        public async Task<JsonResult> Feed()
        {
            var feed = await _manager.GetFeed(User.Identity.Name);
            var tiles = new List<TileViewModel>();
            foreach (var tile in feed)
            {
                tiles.Add(new TileViewModel
                {
                    Image = tile.ProfilePicture,
                    Active = tile.Availability
                });
            }

            return Json(tiles, JsonRequestBehavior.AllowGet);
        }
    }
}

Sinbin.Web/Controllers/ProfileController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Sinbin.FileUpload;
using Sinbin.UserManager;
using Sinbin.Web.Helpers;
using Sinbin.Web.Models;

namespace Sinbin.Web.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        #region Varibles

        private ApplicationUserManager _userManager;
        private readonly IFileStorage _fileStorage;
        #endregion

        #region Properties
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion

        #region Constructors

        public ProfileController()
        {
            _fileStorage = new AmazonFileStorage();
        }
        #endregion

        #region Controllers
        // GET: Profile/Picture
        [Authorize]
        public async Task<ActionResult> Picture()
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var viewModel = new PictureViewModel
            {
                ProfilePictureUrl = user.ProfilePicture,
            };

            return View(viewModel);
        }

        // GET: Profile/Picture
        [HttpGet]
        [Authorize]
        public async Task<JsonResult> PictureSrc()
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var viewModel = new PictureViewModel
            {
                ProfilePictureUrl = user.ProfilePicture,
            };
            return Json(viewModel);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Picture(PictureViewModel model)
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            if (user != null)
            {
                // if newly posted file
                if (model.ProfilePicture != null)
                {
                    var url = _fileStorage.Write(FileHelpers.ConvertEmailToFileName(user.Email, model.ProfilePicture.FileName),
                    FileHelpers.GetPostedFileBytes(model.ProfilePicture));
                    if (string.IsNullOrEmpty(url))
                    {
                        // display error
                    }
                    user.ProfilePicture = url;
                }
                UserManager.Update(user);
                // add randomId parameter so that the css will pull the updated
                // profile picture rather than the cached. This is because the url
                // always remains the same for the user
                model.ProfilePictureUrl = user.ProfilePicture + $"?randomId={ Guid.NewGuid() }";
            }
            return View(model);
        }
        #endregion
    }
}

Sinbin.Web/Controllers/SettingsController.cs
using System.Web.Mvc;

namespace Sinbin.Web.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        [HttpGet]
        [Authorize]
        public ActionResult Menu()
        {
            return View();
        }
    }
}

Sinbin.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

Sinbin.Web/Views/Shared/_NavbarLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/navbar")
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <img id="Logo" class="nav-logo" src="../../Images/hilo_new.png" alt="Hilo" />
                    <input id="statusToggle" type="checkbox" data-toggle="toggle" data-style="ios" data-width="20" data-on=" " data-off=" " data-onstyle="success" data-offstyle="danger">
                </div>
            </div>
        </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    <nav id="footer-nav" class="navbar navbar-default navbar-fixed-bottom">
        <div class="container">
            <div class="col-xs-4 text-center">
                <a href="@Url.Action("Index", "Feed")">
                    <img id="FeedIcon" class="nav-icon" src="../../Images/home-inactive.png" alt="Feed"/>
                </a>
            </div>
            <div class="col-xs-4 text-center">
                <a href="@Url.Action("Picture", "Profile")">
                    <img id="MeIcon" class="nav-icon" src="../../Images/camera-inactive.png" alt="Me" />
                </a>
            </div>          
            <div class="col-xs-4 text-center">
                <a href="@Url.Action("Menu", "Settings")">
                    <img id="SettingsIcon" class="nav-icon" src="../../Images/settings-inactive.png" alt="Settings" />
                </a>
            </div>
        </div>
    </nav>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/loadImage")
    @Scripts.Render("~/bundles/navigation")
    @RenderSection("scripts", required: false)
</body>
</html>